config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments, :only => [:create, :destroy, :edit]
  end
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index
        @article = Article.all
    end

    def show
        @comment = Comment.new
        @comments = @article.comments.includes(:article)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new article_params
        if @article.save
            flash[:success] = "作成に成功しました"
            redirect_to :root
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update_attributes article_params
            flash[:success] = "更新に成功しました"
            redirect_to :root
        else
            render  :edit
        end
            
    end

    def destroy
        if @article.destroy
            flash[:success] = "削除に成功しました"
        else
            flash[:error] = "削除に失敗しました"
        end
        redirect_to :root
    end
    
    private
    def set_article
         @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(
            :name,
            :title,
            :content
        )
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article
    before_action :set_comment, only: [:update, :destroy]
    
    def update
        if @comment.update_attributes comment_params
            flash[:success] = "更新に成功しました"
        else
            flash[:error] = "更新に失敗しました"
        end
        redirect_to @article
    end
    
    def create
        if @article.comments.create comment_params
            flash[:success] = "コメントしました"
        else
            flash[:error] = "コメントに失敗しました"
        end
        redirect_to @article
    end
    
    def destroy
        if @comment.destroy
            flash[:success] = "コメントを削除しました"
        else
            flash[:error] = "コメントの削除に失敗しました"
        end
        redirect_to @article
    end
    
    private
        def comment_params
            params.require(:comment).permit(
                :from,
                :body
            )
        end
        
        def set_article
            @article = Article.find(params[:article_id])
        end
        
        def set_comment
            @comment = Comment.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.slim
= link_to article
  li.list-group-item id="article-#{article.id}"
    span.title = article.title

app/views/articles/_form.html.slim
= form_for @article do |f|
  
  .form-group
    = f.label "名前"
    = f.text_field :name, class: "form-control"

  .form-group
    = f.label "タイトル"
    = f.text_field :title, class: "form-control"

  .form-group
    = f.label "内容"
    = f.text_area :content, class: "form-control"

  = f.submit "投稿する", class: "btn btn-primary"

app/views/articles/edit.html.slim
h1 記事の編集
= render 'form'

app/views/articles/index.html.slim
h1 投稿記事一覧
= link_to '新規作成', new_article_path
ul
  = render @article

app/views/articles/new.html.slim
h1 新規作成
= render 'form'

app/views/articles/show.html.slim
h1
  = @article.title
h2
  = "投稿者:"
  = @article.name
p 
  = @article.content

div
  div
    = button_to edit_article_path, method: :get
      span 編集する
    = button_to @article, method: :delete, data: { confirm: "本当に削除しますか？" }
      span 削除する

h2 コメント一覧
- if @comments.any?
    p
      - @article.comments.each do |comment|
        = comment.from
        = ":"
        = comment.body
        br
        = button_to "削除", [@article, comment], method: :delete, data: { confirm: "本当に削除しますか？" }
        br
- else
  p コメントはありません
  
h2 コメントを書く
= render 'comments/form', { comment: @comment, button_string: "コメントする" }

=link_to 'トップに戻る', root_path

app/views/comments/_comment.html.slim
div id="comment-#{comment.id}"
  div.from 
    div 名前
    = comment.from
  div.body
    div コメント
    = comment.body
  div
    = render 'comments/form' , { comment: comment, button_string: "更新する" }

app/views/comments/_form.html.slim
= form_for [@article, comment] do |f|

  .form-group
    = f.label "名前"
    br
    = f.text_field :from, class: "form-control"

  .form-group
    = f.label "コメント"
    br
    = f.text_field :body, class: "form-control"
    
  = f.submit button_string

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>